const t="1G1UjWN_ru3PdQf-qlKuwIT5CCfQSuA6reOzQZdu6FW8";const o="AIzaSyAmOoWpQprHyZS97DiIXCdy2LFkAe0POa8";const f={t:`https://sheets.googleapis.com/v4/spreadsheets/${t}/values/Navbar?key=${o}`,body:`https://sheets.googleapis.com/v4/spreadsheets/${t}/values/Body?key=${o}`,o:`https://sheets.googleapis.com/v4/spreadsheets/${t}/values/Header?key=${o}`,i:`https://sheets.googleapis.com/v4/spreadsheets/${t}/values/Footer?key=${o}`};const b=async t=>{try{const o=await fetch(t);if(!o.ok)throw new Error("Failed to fetch data");return o.json()}catch(t){console.error("Error:",t);return null}};const n=document.getElementById("hamburger");const c=document.getElementById("nav-links");n.addEventListener("click",()=>{n.classList.toggle("active");c.classList.toggle("active")});const s=async()=>{const t=await b(f.t);const n=document.getElementById("nav-links");const o=document.getElementById("logo-image");const c=t.values.slice(1);n.innerHTML="";const s=c.find(t=>t[0]==="Logo");if(s){o.src=s[1];o.alt=s[2]||"Logo"}c.filter(t=>t[0]==="Link").forEach(t=>{const o=document.createElement("a");o.href=t[2];o.textContent=t[1];o.target="_blank";n.appendChild(o)})};const e=async()=>{const t=await b(f.o);const o=document.getElementById("header-carousel");const c=document.createElement("div");c.className="carousel-dots";let s=0;let n=0;let e=0;const a=t.values.slice(1).map((t,o)=>{const n=document.createElement("div");n.className="carousel-slide";n.style.backgroundImage=`url('${t[0]}')`;const c=document.createElement("div");c.className="carousel-content";c.innerHTML=`
            <h2>
                <a href="${t[3]}" target="_blank">${t[1]}</a>
            </h2>
            <p>${t[2]}</p>
        `;n.appendChild(c);if(o===0)n.classList.add("active");return n});const i=n=>{a.forEach((t,o)=>{if(o===n){t.classList.add("active")}else{t.classList.remove("active")}});c.children[s].classList.remove("active");s=n;c.children[s].classList.add("active")};a.forEach((t,o)=>{const n=document.createElement("div");n.className="carousel-dot";if(o===0)n.classList.add("active");n.addEventListener("click",()=>{i(o)});c.appendChild(n)});o.append(...a,c);o.addEventListener("touchstart",t=>{n=t.touches[0].clientX});o.addEventListener("touchmove",t=>{e=t.touches[0].clientX});o.addEventListener("touchend",()=>{if(n-e>50){const t=(s+1)%a.length;i(t)}else if(n-e<-50){const o=(s-1+a.length)%a.length;i(o)}});setInterval(()=>{const t=(s+1)%a.length;i(t)},5e3)};const a=async()=>{const l=await b(f.body);const d=document.getElementById("content");const c=document.getElementById("tag-filter");const s=document.getElementById("search-bar");const t=document.getElementById("search-button");const o=document.getElementById("pagination");const n=3;let e=1;const a=[...new Set(l.values.slice(1).flatMap(t=>t[2].split(",").map(t=>t.trim())))];c.innerHTML+=a.map(t=>`<option value="${t}">${t}</option>`).join("");const i=()=>window.innerWidth<=768;const r=(e="",a="",t=1)=>{const o=window.matchMedia("(max-width: 768px)").matches;const n=o?3:6;const c=l.values.slice(1).filter(t=>{const o=t[1].toLowerCase().includes(e);const n=t[3].toLowerCase().includes(e);const c=t[2].toLowerCase().includes(e);const s=a===""||t[2].split(",").map(t=>t.trim()).includes(a);return(o||n||c)&&s});const s=Math.ceil(c.length/n);const i=(t-1)*n;const r=c.slice(i,i+n);d.innerHTML=r.map(t=>{const o=t[2].split(",").map(t=>`<span class="card-tag">${t.trim()}</span>`).join("");const n=100;const c=t[3].length>n;const s=t[3].slice(0,n);return`
                <div class="card">
                    <img src="${t[0]}" alt="${t[1]}">
                    <div class="card-body">
                        <div class="card-tags">${o}</div>
                        <h3 class="card-title">
                            <a href="${t[4]}" target="_blank">${t[1]}</a>
                        </h3>
                        <p class="card-description" data-full="${t[3]}" data-short="${s}">
                            ${c?s+"...":t[3]}
                        </p>
                        ${c?`<button class="toggle-description">See More</button>`:""}
                    </div>
                </div>
            `}).join("");document.querySelectorAll(".toggle-description").forEach(c=>{c.addEventListener("click",t=>{const o=c.previousElementSibling;const n=c.textContent==="Hide";if(n){o.textContent=o.getAttribute("data-short")+"...";c.textContent="See More"}else{o.textContent=o.getAttribute("data-full");c.textContent="Hide"}})});h(t,s)};const u=t=>{const o=s.value.toLowerCase();const n=c.value;r(o,n,t)};window.addEventListener("resize",()=>{const t=s.value.toLowerCase();const o=c.value;r(t,o,1)});const h=(o,n)=>{const c=document.getElementById("pagination");c.innerHTML="";if(n<=1){c.style.display="none";return}c.style.display="flex";const t=document.createElement("button");t.textContent="Previous";t.className="pagination-btn";if(o===1){t.disabled=true;t.classList.add("disabled")}t.addEventListener("click",()=>u(o-1));c.appendChild(t);for(let t=1;t<=n;t++){const e=document.createElement("button");e.textContent=t;e.className="pagination-btn";if(t===o){e.classList.add("active")}e.addEventListener("click",()=>u(t));c.appendChild(e)}const s=document.createElement("button");s.textContent="Next";s.className="pagination-btn";if(o===n){s.disabled=true;s.classList.add("disabled")}s.addEventListener("click",()=>u(o+1));c.appendChild(s)};t.addEventListener("click",()=>{const t=s.value.toLowerCase();const o=c.value;e=1;r(t,o,e)});s.addEventListener("input",()=>{const t=s.value.toLowerCase();const o=c.value;e=1;r(t,o,e)});c.addEventListener("change",()=>{const t=s.value.toLowerCase();const o=c.value;e=1;r(t,o,e)});r()};const i=async()=>{const t=await b(f.i);const s=t.values.slice(1);const o=document.getElementById("footer-address");const n=document.getElementById("footer-links");const c=document.getElementById("footer-contact");o.innerHTML="";n.innerHTML="";c.innerHTML="";const e=s.find(t=>t[0]==="Address"&&t[1]==="Title")[2];const a=s.find(t=>t[0]==="Address"&&t[1]==="Content")[2];o.innerHTML=`
        <h4>${e}</h4>
        <p>${a}</p>
    `;const i=s.find(t=>t[0]==="Sitelink"&&t[1]==="Title")[2];const r=s.filter(t=>t[0]==="Sitelink"&&t[1].includes("Link Text"));n.innerHTML=`<h4>${i}</h4><ul></ul>`;const l=n.querySelector("ul");r.forEach(o=>{const t=o[2];const n=s.find(t=>t[0]==="Sitelink"&&t[1]===o[1].replace("Text","URL"));const c=n?n[2]:"#";l.innerHTML+=`<li><a href="${c}" target="_blank">${t}</a></li>`});const d=s.find(t=>t[0]==="Contact"&&t[1]==="Title")[2];const u=s.find(t=>t[0]==="Contact"&&t[1]==="Email Label")[2];const h=s.find(t=>t[0]==="Contact"&&t[1]==="Email Address")[2];const p=s.find(t=>t[0]==="Contact"&&t[1]==="Phone Label")[2];const m=s.find(t=>t[0]==="Contact"&&t[1]==="Phone Number")[2];const $=s.find(t=>t[0]==="Contact"&&t[1]==="Social Label")[2];const g=s.find(t=>t[0]==="Contact"&&t[1]==="Social Facebook")[2];const v=s.find(t=>t[0]==="Contact"&&t[1]==="Social Instagram")[2];c.innerHTML=`
        <h4>${d}</h4>
        <p>${u}: <a href="mailto:${h}">${h}</a></p>
        <p>${p}: <a href="tel:${m}">${m}</a></p>
        <p>${$}: 
            <a href="${g}" target="_blank">Facebook</a> | 
            <a href="${v}" target="_blank">Instagram</a>
        </p>
    `};const r=async(t,o)=>{const n=localStorage.getItem(o);if(n)return JSON.parse(n);const c=await b(t);if(c)localStorage.setItem(o,JSON.stringify(c));return c};const l=async()=>{await s();await e();await a();await i()};l();